openapi: 3.0.0
info:
  version: 1.0.0
  title: Integration.Demo
  description: Integration.Demo.Swagger v1
paths: {}
servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/Sherpian/Integration.Demo/1.0.0